version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: humanize
    versions:
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: django-cachalot
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: cryptography
    versions:
    - 3.3.1
    - "3.4"
  - dependency-name: django-debug-toolbar
    versions:
    - "3.2"
- package-ecosystem: npm
  directory: "/components"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: fullcalendar
    versions:
    - 5.5.1
  - dependency-name: datatables.net
    versions:
    - 1.10.23
  - dependency-name: datatables.net-bs
    versions:
    - 1.10.23
  - dependency-name: flot
    versions:
    - 4.2.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: dev
  labels:
  - dependencies
  ignore:
  - dependency-name: nginx
    versions:
    - 1.19.6.pre.alpine
    - 1.19.7.pre.alpine
    - 1.19.8.pre.alpine
    - 1.19.9.pre.alpine
  - dependency-name: python
    versions:
    - 3.9.1.pre.slim.pre.buster
    - 3.9.2.pre.slim.pre.buster
    - 3.9.3.pre.slim.pre.buster
